Fluentd support
aptible/joecool pull request #25
Opened 2021-05-07 04:29 UTC by mdelaossa

Necessary to be able to send data to https://github.com/aptible/gentlemanjerry/pull/48

2021-05-11 17:15 UTC, almathew requested changes
We should be able to re-enable tests before actually merging this. We can use whatever images you're creating for testing in the meantime

2021-05-24 22:20 UTC, mdelaossa commented
I still haven't switched to using `joecool-v3`, but I'm asking for another review because I re-enabled the tests we had had to remove.

I first tried using netcat, then openssl s_server, then finally socat to read GJ's output (this commit https://github.com/aptible/joecool/pull/25/commits/65d171315beeb82520fcae45944718a42262db45 ) but it was a dead end as fluentd when set to logstash uses a binary format 🤦 

So I had to go back to using Redis so we could test that our config worked. It's not ideal, since we're not testing the logstash output, but this way we still see that we're sending the log lines we care about https://github.com/aptible/joecool/pull/25/commits/aa6304bade09368652722bf5338abf915dd48b4e

2021-06-04 13:19 UTC, almathew approved these changes

2022-02-22 19:45 UTC, merged

2022-02-22 19:45 UTC, almathew commented
I'm merging this into a `fluentd` branch and making this a protected branch since tails don't use fluentd